version: "3"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "ctf"
    restart: always
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    
  app:
    build: ./app
    environment:
      - APP_SECRET
      - DATABASE_URL
      - IMAGE_SERVICE_HOST
      - ADMIN_PASSWORD
    restart: always
  
  service:
    build: ./service
    environment:
      - APP_SECRET
    restart: always

  nginx:
    image: nginx
    restart: always
    ports:
      - "10001:10001"
      - "10002:10002"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/html:/usr/share/nginx/html:ro"
