version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 7777:80
    networks: 
      osu:

  imi:
    build:
      context: ./imi-src
      dockerfile: Dockerfile
    networks: 
      osu:

networks:
  osu: